provider: gemini 
model: gemini-3-flash-preview 
context_window: 120000 
embedding_model: gemini-embedding-001
embedding_top_k: 5
stream: true
llm_max_retries: 3
llm_retry_delay: 2.0
checkpoint_file: .agentchanti_checkpoint.json
ollama_base_url: http://localhost:11434/api/generate
lm_studio_base_url: http://localhost:1234/v1
openai:
  api_key: ''
  base_url: https://api.openai.com/v1
gemini:
  api_key: 'AIzaSyDB1DYoxMfq-sJO7ZI5nNxW59HF_m583vo'
  base_url: https://generativelanguage.googleapis.com/v1beta
anthropic:
  api_key: ''
  base_url: https://api.anthropic.com/v1
models: {}
prompts:
  planner_suffix: every response should contain readable explanation.
  coder_suffix: every response should contain readable explanation.
  reviewer_suffix: every response should contain readable explanation.
embedding_cache_dir: .agentchanti
report_dir: .agentchanti/reports
step_cache_ttl_hours: 24
plugins: []
budget_limit: 0.0
kb_registry_owner: ''
kb_registry_repo: agentchanti-kb-registry
kb_registry_auto_update: true
pricing:
  gpt-4o:
    input: 2.5
    output: 10.0
  gpt-4o-mini:
    input: 0.15
    output: 0.6
  gpt-4-turbo:
    input: 10.0
    output: 30.0
  gpt-4:
    input: 30.0
    output: 60.0
  gpt-3.5-turbo:
    input: 0.5
    output: 1.5
  claude-3-5-sonnet:
    input: 3.0
    output: 15.0
  claude-3-opus:
    input: 15.0
    output: 75.0
  claude-3-haiku:
    input: 0.25
    output: 1.25
  deepseek-coder:
    input: 0.14
    output: 0.28
  gemini-2.0-flash:
    input: 0.1
    output: 0.4
  gemini-2.5-pro:
    input: 1.25
    output: 10.0
  gemini-2.5-flash:
    input: 0.15
    output: 0.6
  claude-sonnet-4:
    input: 3.0
    output: 15.0
  claude-haiku-4:
    input: 0.8
    output: 4.0
